 spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 30Wish*GK
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    jpa:
      show-sql: true
  redis:
    host: localhost
    port: 6379
 girl:
    name: guodongchang2
    age: 24
